---
- name: Build and Deploy Docker Image to Kubernetes
  hosts: localhost
  connection: local
  vars_files:
    - ./vault.yml

  tasks:
    - name: Log in to Docker Hub
      community.general.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
        reauthorize: yes

    - name: Build Docker image
      docker_image:
        build:
          path: "{{ dockerfile_path | default('./') }}"
        name: "{{ dockerhub_username }}/{{ image_name | default('country-service') }}:{{ image_tag | default('0.0.11') }}"
        source: build
        state: present
        tag: "{{ image_tag | default('0.0.11') }}"

    - name: Push the Docker image to Docker Hub
      docker_image:
        name: "{{ dockerhub_username }}/{{ image_name | default('country-service') }}:{{ image_tag | default('0.0.11') }}"
        tag: "{{ image_tag | default('0.0.11') }}"
        push: yes
        source: local

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: my-deployment.yaml
        kubeconfig: config

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: service.yaml
        kubeconfig: config
