- name: Build and Deploy Docker Image to Kubernetes
  hosts: localhost # or your build/deployment server
  connection: local

  vars:
    image_name: my-country-service
    image_tag: v1
    dockerfile_path: .

  tasks:
    - name: Log in to Docker Hub
      community.general.docker_login:
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
        reauthorize: yes

    - name: Build Docker image
      docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        state: present
        push: true
    - name: Push the Docker image to Docker Hub
      docker_image:
        name: "{{ docker_registry_username }}/{{ image_name }}:{{ image_tag }}"
        push: yes
        source: local

    - name: Pull Docker image (optional, for verification or on target nodes)
      docker_image:
        name: "{{ lookup('env', 'DOCKER_USERNAME') }}/{{ image_name }}:{{ image_tag }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Create virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv "{{ ansible_env.HOME }}/.local/venv"
        creates: "{{ ansible_env.HOME }}/.local/venv"

    - name: Install kubernetes package in virtual environment
      ansible.builtin.pip:
        name: kubernetes
        state: present
        virtualenv: "{{ ansible_env.HOME }}/.local/venv"
      environment:
        PATH: "{{ ansible_env.HOME }}/.local/venv/bin:{{ ansible_env.PATH }}"

    - name: Set fact for Python interpreter
      ansible.builtin.set_fact:
        ansible_python_interpreter: "{{ ansible_env.HOME }}/.local/venv/bin/python3"

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: my-deployment.yaml
        kubeconfig: config # Path to your kubeconfig file

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: service.yaml
        kubeconfig: config
