- name: Build and Deploy Docker Image to Kubernetes
  hosts: localhost
  connection: local

  vars:
    image_name: my-country-service
    image_tag: v1
    dockerfile_path: .

  tasks:
    - name: Log in to Docker Hub
      community.general.docker_login:
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
        reauthorize: yes

    - name: Build Docker image
      docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "{{ lookup('env', 'DOCKER_USERNAME') }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        state: present
        push: true

    - name: Push the Docker image to Docker Hub
      docker_image:
        name: "{{ lookup('env', 'DOCKER_USERNAME') }}/{{ image_name }}:{{ image_tag }}"
        push: yes
        source: local

    - name: Pull Docker image (optional, for verification)
      docker_image:
        name: "{{ lookup('env', 'DOCKER_USERNAME') }}/{{ image_name }}:{{ image_tag }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Check for Jenkins-provided venv python
      ansible.builtin.stat:
        path: /var/jenkins_home/ansible_venv/bin/python3
      register: jenkins_venv
      changed_when: false

    - name: Set ansible to use Jenkins venv Python
      ansible.builtin.set_fact:
        ansible_python_interpreter: /var/jenkins_home/ansible_venv/bin/python3
      when: jenkins_venv.stat.exists

    - name: Install kubernetes package in Jenkins venv if missing
      ansible.builtin.pip:
        name: kubernetes
        state: present
        virtualenv: /var/jenkins_home/ansible_venv
        virtualenv_command: python3 -m venv
      when: jenkins_venv.stat.exists

    - name: Set ansible to use system python if no venv
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3
      when: not jenkins_venv.stat.exists

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: my-deployment.yaml
        kubeconfig: config

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: service.yaml
        kubeconfig: config
