apiVersion: v1
kind: Service
metadata:
  name: my-country-service
  namespace: jenkins
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8082"
  labels:
    app: country-service
spec:
  selector:
    app: country-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
